### ISSUE TITLE
What would happen if I used objects that were not perfectly masked?

### ISSUE THREAD

**Issue by magi-1** [junxuan-li/Neural-Reflectance-PS#2]
For example, say I want to model something that is resting on the table that is not perfectly blank. Will this affect the inverse rendering of the object?

Great work by the way. Taking into account the shadows is key for this problem.

**Comment by junxuan-li** [comment]
It depends on how strong the inter-reflection is between the background and the target object. If the inter-reflection is quite noticeable, violating the rendering equation, the inverse rendering won't work well.
